export const API_ENDPOINT = 'http://hackathon.jay.li:4000/api';

export const GAME_STATE = {
  INIT: 'INIT',
  READY: 'READY',
  WAITING_FOR_OPPONENT: 'WAITING_FOR_OPPONENT',
  BATTLE_IN_PROGRESS: 'BATTLE_IN_PROGRESS',
  GAME_OVER: 'GAME_OVER',
  VICTORY: 'VICTORY'
};
